package com.zenith.plugin.opencraft.update;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.zenith.plugin.opencraft.BuildConstants;
import com.zenith.plugin.opencraft.OpenCraftConfig;
import net.kyori.adventure.text.logger.slf4j.ComponentLogger;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.time.Duration;
import java.time.Instant;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.concurrent.Executor;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import static com.zenith.Globals.EXECUTOR;

/**
 * Checks for plugin updates from GitHub Releases, optionally downloads and
 * stages the new JAR, and verifies its SHA-256 checksum before applying.
 *
 * Update channels:
 * 
 *   - stable — only non-prerelease tags (e.g., v1.0.0)
 *   - beta   — stable + beta pre-releases (e.g., v1.0.0-beta.1)
 *   - dev    — any release tag
 * 
 *
 * A .sha256 file (generated by CI) must accompany every release JAR.
 * If the checksum cannot be verified, the download is rejected.
 */
public final class PluginUpdateService {

    private static final String REPO_OWNER  = "PoseidonsCave";
    private static final String REPO_NAME   = "opencraft";
    private static final URI RELEASES_URI   = URI.create(
        "https://api.github.com/repos/" + REPO_OWNER + "/" + REPO_NAME + "/releases");
    private static final URI LATEST_URI     = URI.create(RELEASES_URI + "/latest");

    private final OpenCraftConfig       config;
    private final ComponentLogger logger;
    private final HttpClient      httpClient;
    private final Gson            gson;
    private final Executor        executor;
    private final Path            currentJarPath;
    private final Path            pluginsDir;

    private volatile UpdateStatus status = UpdateStatus.NOT_CHECKED;

    public PluginUpdateService(final OpenCraftConfig config, final ComponentLogger logger) {
        this.config     = config;
        this.logger     = logger;
        this.gson       = new Gson();
        this.httpClient = HttpClient.newBuilder()
            .followRedirects(HttpClient.Redirect.ALWAYS)
            .connectTimeout(Duration.ofSeconds(5))
            .build();
        // Reuse ZenithProxy's shared executor for one-off update checks/downloads.
        // runUpdateCycle is synchronized so concurrent submissions serialize.
        this.executor = EXECUTOR;
        this.currentJarPath = resolveCurrentJar();
        this.pluginsDir     = resolvePluginsDir(this.currentJarPath);
    }

    public enum UpdateStatus { NOT_CHECKED, CHECKING, UP_TO_DATE, UPDATE_AVAILABLE, STAGED, FAILED }

    public void scheduleStartupCheck() {
        if (!config.updateCheckOnLoad) return;
        executor.execute(() -> {
            final var result = runUpdateCycle(config.updateAutoDownload);
            logResult(result);
        });
    }

    public UpdateResult checkForUpdates() {
        return runUpdateCycle(false);
    }

    public UpdateResult checkAndStageUpdate() {
        return runUpdateCycle(true);
    }

    public UpdateStatus getStatus() { return status; }

    // ── Core update cycle ─────────────────────────────────────────────────────

    private synchronized UpdateResult runUpdateCycle(final boolean stageIfAvailable) {
        status = stageIfAvailable ? UpdateStatus.CHECKING : UpdateStatus.CHECKING;

        try {
            final ReleaseInfo release = fetchRelease(config.updateChannel);

            if (!isNewer(BuildConstants.VERSION, release.version())) {
                status = UpdateStatus.UP_TO_DATE;
                return UpdateResult.upToDate(BuildConstants.VERSION);
            }

            if (!stageIfAvailable) {
                status = UpdateStatus.UPDATE_AVAILABLE;
                return UpdateResult.available(BuildConstants.VERSION, release.version());
            }

            return stageRelease(release);

        } catch (final Exception e) {
            status = UpdateStatus.FAILED;
            logger.warn("[OpenCraft] Update check failed: {}", e.getMessage());
            return UpdateResult.failed(e.getMessage());
        }
    }

    private UpdateResult stageRelease(final ReleaseInfo release)
        throws IOException, InterruptedException {
        Files.createDirectories(pluginsDir);

        final Path target = pluginsDir.resolve(
            BuildConstants.PLUGIN_ID + "-" + release.version() + ".jar");

        // Skip if already staged
        if (Files.exists(target) && verifyExistingStage(target, release)) {
            status = UpdateStatus.STAGED;
            return UpdateResult.alreadyStaged(release.version(), target);
        }

        final Path tmp = Files.createTempFile(pluginsDir, BuildConstants.PLUGIN_ID + "-", ".download");
        try {
            // Download JAR
            downloadAsset(release.downloadUri(), tmp);

            // Verify SHA-256 checksum
            final String expectedChecksum = fetchExpectedChecksum(release);
            final String actualChecksum   = sha256hex(tmp);
            if (!expectedChecksum.equalsIgnoreCase(actualChecksum)) {
                throw new IOException("Checksum mismatch — expected " + expectedChecksum +
                    ", got " + actualChecksum + ". Rejecting download.");
            }

            // Verify embedded plugin metadata
            verifyJarMetadata(tmp, release.version());

            Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
            status = UpdateStatus.STAGED;
            logger.info("[OpenCraft] Update staged: {}. Restart ZenithProxy to apply.", target.getFileName());
            return UpdateResult.staged(release.version(), target);

        } catch (final Exception e) {
            Files.deleteIfExists(tmp);
            throw e;
        }
    }

    // ── GitHub API helpers ────────────────────────────────────────────────────

    private ReleaseInfo fetchRelease(final String channel) throws IOException, InterruptedException {
        final URI uri = "stable".equalsIgnoreCase(channel) ? LATEST_URI : RELEASES_URI;
        final String body = get(uri);
        final var json = gson.fromJson(body, com.google.gson.JsonElement.class);

        if (json.isJsonArray()) {
            // For beta/dev channels, pick most recent applicable release
            return json.getAsJsonArray().asList().stream()
                .map(JsonElement::getAsJsonObject)
                .filter(r -> acceptForChannel(r, channel))
                .findFirst()
                .map(this::parseRelease)
                .orElseThrow(() -> new IOException("No applicable release found for channel: " + channel));
        } else {
            return parseRelease(json.getAsJsonObject());
        }
    }

    private boolean acceptForChannel(final JsonObject release, final String channel) {
        final boolean prerelease = release.has("prerelease") && release.get("prerelease").getAsBoolean();
        return switch (channel.toLowerCase(Locale.ROOT)) {
            case "dev"  -> true;
            case "beta" -> true; // includes both stable and beta
            default     -> !prerelease; // stable only
        };
    }

    private ReleaseInfo parseRelease(final JsonObject json) {
        final String tag     = json.get("tag_name").getAsString();
        final String version = tag.startsWith("v") ? tag.substring(1) : tag;
        final var assets     = json.getAsJsonArray("assets");

        final Optional<JsonObject> jarAsset = assets.asList().stream()
            .map(JsonElement::getAsJsonObject)
            .filter(a -> a.get("name").getAsString().endsWith(".jar"))
            .max(Comparator.comparingInt(a -> jarScore(a.get("name").getAsString())));

        final Optional<JsonObject> sha256Asset = assets.asList().stream()
            .map(JsonElement::getAsJsonObject)
            .filter(a -> a.get("name").getAsString().endsWith(".jar.sha256"))
            .findFirst();

        if (jarAsset.isEmpty()) throw new IllegalStateException("No JAR asset in release " + tag);

        return new ReleaseInfo(
            version,
            URI.create(jarAsset.get().get("browser_download_url").getAsString()),
            sha256Asset.map(a -> URI.create(a.get("browser_download_url").getAsString())).orElse(null)
        );
    }

    private int jarScore(final String name) {
        int s = 0;
        if (name.contains(BuildConstants.PLUGIN_ID)) s += 50;
        return s;
    }

    private String fetchExpectedChecksum(final ReleaseInfo release)
        throws IOException, InterruptedException {
        if (release.checksumUri() == null) {
            throw new IOException("Release does not include a .sha256 file. Cannot verify integrity.");
        }
        return get(release.checksumUri()).strip().split("\\s+")[0];
    }

    private void downloadAsset(final URI uri, final Path dest)
        throws IOException, InterruptedException {
        final HttpResponse<InputStream> resp = httpClient.send(
            HttpRequest.newBuilder(uri)
                .header("User-Agent", "OpenCraft/" + BuildConstants.VERSION)
                .timeout(Duration.ofSeconds(60))
                .GET().build(),
            HttpResponse.BodyHandlers.ofInputStream());
        if (resp.statusCode() >= 400) {
            throw new IOException("Asset download returned HTTP " + resp.statusCode());
        }
        try (InputStream in = resp.body()) {
            Files.copy(in, dest, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private String get(final URI uri) throws IOException, InterruptedException {
        final HttpResponse<String> resp = httpClient.send(
            HttpRequest.newBuilder(uri)
                .header("User-Agent", "OpenCraft/" + BuildConstants.VERSION)
                .header("Accept", "application/vnd.github+json")
                .timeout(Duration.ofSeconds(10))
                .GET().build(),
            HttpResponse.BodyHandlers.ofString());
        if (resp.statusCode() >= 400) {
            throw new IOException("GitHub API returned HTTP " + resp.statusCode());
        }
        return resp.body();
    }

    // ── Integrity helpers ─────────────────────────────────────────────────────

    private static String sha256hex(final Path file) throws IOException {
        try {
            final MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(Files.readAllBytes(file));
            return HexFormat.of().formatHex(md.digest());
        } catch (final Exception e) {
            throw new IOException("SHA-256 computation failed: " + e.getMessage());
        }
    }

    private void verifyJarMetadata(final Path jar, final String expectedVersion) throws IOException {
        try (ZipFile zip = new ZipFile(jar.toFile())) {
            final ZipEntry entry = zip.getEntry("zenithproxy.plugin.json");
            if (entry == null) throw new IOException("Downloaded JAR missing zenithproxy.plugin.json");
            try (InputStream in = zip.getInputStream(entry)) {
                final JsonObject meta = gson.fromJson(new String(in.readAllBytes()), JsonObject.class);
                final String id = meta.get("id").getAsString();
                if (!BuildConstants.PLUGIN_ID.equals(id)) {
                    throw new IOException("Downloaded JAR plugin id '" + id + "' does not match expected '" + BuildConstants.PLUGIN_ID + "'");
                }
            }
        }
    }

    private boolean verifyExistingStage(final Path jar, final ReleaseInfo release) {
        try {
            verifyJarMetadata(jar, release.version());
            return true;
        } catch (final Exception e) {
            return false;
        }
    }

    // ── Version comparison ────────────────────────────────────────────────────

    static boolean isNewer(final String current, final String candidate) {
        final int[] c = parseVersion(current);
        final int[] n = parseVersion(candidate);
        for (int i = 0; i < Math.max(c.length, n.length); i++) {
            final int cv = i < c.length ? c[i] : 0;
            final int nv = i < n.length ? n[i] : 0;
            if (nv > cv) return true;
            if (nv < cv) return false;
        }
        return false;
    }

    private static int[] parseVersion(final String v) {
        final String numeric = v.replaceAll("[^0-9.]", "").replaceAll("^\\.+|\\.+$", "");
        final String[] parts = numeric.isEmpty() ? new String[]{"0"} : numeric.split("\\.");
        final int[] result = new int[parts.length];
        for (int i = 0; i < parts.length; i++) {
            try { result[i] = Integer.parseInt(parts[i]); } catch (final NumberFormatException e) { result[i] = 0; }
        }
        return result;
    }

    // ── Path resolution ───────────────────────────────────────────────────────

    private static Path resolveCurrentJar() {
        try {
            return Path.of(PluginUpdateService.class.getProtectionDomain()
                .getCodeSource().getLocation().toURI());
        } catch (final Exception e) {
            return Path.of(BuildConstants.PLUGIN_ID + ".jar");
        }
    }

    private static Path resolvePluginsDir(final Path jar) {
        final Path parent = jar.getParent();
        return (parent != null) ? parent : Path.of("plugins");
    }

    private void logResult(final UpdateResult result) {
        logger.info("[OpenCraft] Update check: {}", result.message());
    }

    // ── Data records ──────────────────────────────────────────────────────────

    private record ReleaseInfo(String version, URI downloadUri, URI checksumUri) {}

    public record UpdateResult(String outcome, String message, String currentVersion,
                                String latestVersion, Path stagedPath) {
        static UpdateResult upToDate(final String v) {
            return new UpdateResult("UP_TO_DATE", "Already up to date (" + v + ").", v, v, null);
        }
        static UpdateResult available(final String current, final String latest) {
            return new UpdateResult("UPDATE_AVAILABLE",
                "Update available: " + latest + " (current: " + current + ").", current, latest, null);
        }
        static UpdateResult staged(final String latest, final Path path) {
            return new UpdateResult("STAGED",
                "Downloaded " + latest + " → " + path.getFileName() + ". Restart to apply.",
                BuildConstants.VERSION, latest, path);
        }
        static UpdateResult alreadyStaged(final String latest, final Path path) {
            return new UpdateResult("ALREADY_STAGED",
                "Version " + latest + " already staged at " + path.getFileName() + ".",
                BuildConstants.VERSION, latest, path);
        }
        static UpdateResult failed(final String reason) {
            return new UpdateResult("FAILED", "Update check failed: " + reason,
                BuildConstants.VERSION, null, null);
        }
    }
}
