package ${maven_group};

/** Auto-generated by the ZenithProxy Gradle plugin. Do not edit manually. */
public final class BuildConstants {
    public static final String VERSION   = "${version}";
    public static final String PLUGIN_ID = "${plugin_id}";
    public static final String MC_VERSION = "${mc_version}";

    private BuildConstants() {}
}
